---

- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: create directory
  file:
    path: /home/ubuntu/alertmanager
    state: directory

- name: download alertmanager tarball
  get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v0.26.0/alertmanager-0.26.0.linux-amd64.tar.gz"
    dest: "/home/ubuntu/alertmanager/alertmanager-0.26.0.linux-amd64.tar.gz"

- name: unpack installation files
  unarchive:
    src: "/home/ubuntu/alertmanager/alertmanager-0.26.0.linux-amd64.tar.gz"
    dest: "/home/ubuntu/alertmanager"
    remote_src: yes

- name: move files
  copy:
    src: "/home/ubuntu/alertmanager/alertmanager-0.26.0.linux-amd64/"
    dest: "/usr/local/bin/alertmanager/"
    remote_src: yes

- name: create service file
  copy:
    dest: "/etc/systemd/system/alertmanager.service"
    content: |
      [Unit]
      Description=Alert Manager Service
      After=network.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/alertmanager/alertmanager --config.file=/usr/local/bin/alertmanager/alertmanager.yml

      [Install]
      WantedBy=multi-user.target

- name: service always started
  systemd:
    name: alertmanager
    state: restarted
    enabled: true
    daemon_reload: yes