---
# tasks file for deploy grafana
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Copy File to Grafana
  shell:  curl https://raw.githubusercontent.com/martindubb/random-stuff/main/grafana/grafana.ini | sudo cp grafana.ini /etc/grafana/grafana.ini

- name: Install nessesary package
  apt: 
      name: apt-transport-https
      state: present
      update_cache: yes

- name: add grafana gpg key
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: add grafana repo 
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Install grafana
  apt: 
      name: grafana
      state: present
      update_cache: yes

- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: grafana-server